In [1]:
str(23).split('2')

['', '3']

In [2]:
len(str(223).split('-2'))-1

0

In [3]:
%%time
sayi(2000000000)

NameError: ignored

In [4]:
import numpy as np


In [10]:
liste = [1,2,3,4,5]
z = np.array(liste)
z

array([1, 2, 3, 4, 5])

In [6]:
a = np.array([1,2,3,4,5])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.shape

(5,)

In [9]:
a.ndim

1

In [11]:
print(a[0])
print(a[3])
print(a[2])

1
4
3


In [12]:
a[3] = 9
print(a)

[1 2 3 9 5]


In [14]:
b = np.array([[1,2,3,4],[5,6,7,8]])

In [15]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
b.ndim

2

In [17]:
b.shape

(2, 4)

In [18]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
c.ndim

2

In [20]:
c.shape

(3, 3)

In [21]:
s = np.zeros((2,2))

print(s)

[[0. 0.]
 [0. 0.]]


In [22]:
s2 = np.ones((2,3))

print(s2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
s5 =np.empty((6,8))

print(s5)

[[2.93737758e-316 3.15538226e-316 3.15541072e-316 3.15534669e-316
  0.00000000e+000 3.22815774e-316 0.00000000e+000 3.15536092e-316]
 [0.00000000e+000 3.15548187e-316 0.00000000e+000 3.15550321e-316
  3.22818382e-316 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 3.15556724e-316 3.15552455e-316 0.00000000e+000
  3.22816248e-316 0.00000000e+000 3.15543206e-316 3.15556013e-316]
 [3.15541784e-316 3.15538938e-316 3.22812928e-316 3.15543918e-316
  3.22819094e-316 0.00000000e+000 3.15536803e-316 0.00000000e+000]
 [3.22814351e-316 3.22817671e-316 3.15554590e-316 3.15548898e-316
  0.00000000e+000 3.15559570e-316 3.15539649e-316 3.22815062e-316]
 [0.00000000e+000 0.00000000e+000 3.15535380e-316 3.15551032e-316
  3.15540361e-316 0.00000000e+000 3.50708981e-316 0.00000000e+000]]


In [25]:
s8 = np.eye(6)

print(s8)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [29]:
s7 = np.arange(1,13,6)

print(s7)

[1 7]


In [32]:
s8 = np.linspace(2,11,5)

print(s8)

[ 2.    4.25  6.5   8.75 11.  ]


In [33]:
s7 = np.random.random((6,6))

print(s7)

[[0.95485086 0.59402159 0.5750239  0.84777783 0.2359262  0.27788139]
 [0.84547759 0.67202471 0.11870845 0.2768819  0.75722973 0.73453992]
 [0.30615018 0.53588174 0.36477398 0.9547111  0.73818883 0.09931945]
 [0.25289487 0.04235387 0.6944446  0.58955105 0.9693756  0.11091626]
 [0.39406771 0.03394156 0.25374583 0.02658163 0.52610203 0.63143221]
 [0.80334231 0.27892101 0.23898986 0.18179992 0.49785456 0.64354183]]


In [35]:
yeni = np.random.randint(1,1000,10)

In [36]:
yeni

array([518, 726, 814, 854, 314, 403,  29,   7, 290, 572])

In [37]:
yeni.argmin()

7

In [38]:
yeni.min()

7

In [39]:
yeni.max()

854

In [40]:
np.argmax(yeni)

3

In [41]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [42]:
dizi = np.array([0,1,2,3,4,5,6,7,8,9]).reshape(5,2)
print('Orijinal Dizi')
dizi

Orijinal Dizi


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
print('Satır Bazlı Birleştirme')
np.concatenate([dizi,dizi],axis=1)

Satır Bazlı Birleştirme


array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7],
       [8, 9, 8, 9]])

In [44]:
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])

In [46]:
a.shape


(3, 4)

In [45]:
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [47]:
print(a[0,1])
b[0,0] = 77
print(a[0,1])

2
77


In [48]:
b = a.copy()

In [50]:
b[1,2] = 42

In [51]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

In [52]:
x.shape

(2, 2)

In [53]:
x+y

array([[ 6,  8],
       [10, 12]])

In [54]:
x-y

array([[-4, -4],
       [-4, -4]])

In [55]:
x*y

array([[ 5, 12],
       [21, 32]])

In [56]:
x**y

array([[    1,    64],
       [ 2187, 65536]])

In [58]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [59]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [60]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [61]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [62]:
s = np.array([[4,9], [25,36]])

In [63]:
np.sqrt(s)

array([[2., 3.],
       [5., 6.]])

In [68]:
x**3

array([[ 1,  8],
       [27, 64]])

In [69]:
x**4

array([[  1,  16],
       [ 81, 256]])

In [65]:
np.exp(3)

20.085536923187668

In [66]:
np.log(s)

array([[1.38629436, 2.19722458],
       [3.21887582, 3.58351894]])

In [70]:
np.log(1000)

6.907755278982137

In [71]:
t = np.array([np.pi/6,np.pi/2,np.pi/3])

In [72]:
np.sin(t)

array([0.5      , 1.       , 0.8660254])

In [73]:
x@y

array([[19, 22],
       [43, 50]])

In [74]:
z.T

array([1, 2, 3, 4, 5])

In [77]:
c = z@z.T # matrisin transpozu ile çarpımı
c

55

In [78]:
np.linalg.matrix_rank(c)

1

In [79]:
c_inv = np.linalg.inv(c)
c_inv

LinAlgError: ignored

In [80]:
c@c_inv

NameError: ignored